global_vars:

    - name: "regexp_ip_address"
      type: "echo"
      params:
          echo: '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'

matches:
    - triggers:
        - ";hw"
        - ";hello world"
      replace: "Hello World!"

